### ISSUE TITLE
Como utilizar esta ferramenta?

### ISSUE THREAD

**Issue by dflourusso** [neves/vwp#1]
Não achei a documentação
![](http://orig09.deviantart.net/4872/f/2016/174/d/0/travalo_by_greenanimator-da7f5zc.gif)

Criar um README para o projeto com a documentação de seu funcionamento e como utilizar.

**Comment by paliari** [comment]
Cade a documentação?

**Comment by FelipeBohnertPaetzold** [comment]
Cadê a documentação?
![](https://pbs.twimg.com/profile_images/841445304406855680/UL0CK2O9.jpg)

**Comment by paliari** [comment]
![ll0dq](https://user-images.githubusercontent.com/2801041/29219305-027bdaa2-7e8e-11e7-9409-3cd01aec464b.gif)
